version: "3.9"

services:
    redis:
        image: "redis:6.2.3"
        container_name: "redis"
        restart: always
        ports: 
            - 6379:6379
        networks: 
            webalytic_net:
                ipv4_address: 172.28.1.2

    clickhouse:
        image: "yandex/clickhouse-server:21.6.4.26-alpine"
        container_name: "clickhouse"
        restart: always
        volumes:
            - "/Users/tmorozov/Projects/data/clickhouse:/var/lib/clickhouse"
        ports: 
            - 8123:8123
            - 9000:9000
            - 9363:9363
        networks: 
            webalytic_net:
                ipv4_address: 172.28.1.5

    collector:
        image: "collector"
        container_name: "webalytic_collector"
        restart: always
        volumes:
            - "/Users/tmorozov/Projects/data/webalytic:/mnt/log"
        environment: 
            - APP_NAME=collector
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_STREAM=${REDIS_STREAM}
            - REDIS_HANDLER=${REDIS_HANDLER}
            - REDIS_GROUP=${REDIS_GROUP}
            - LOG_LEVEL=${LOG_LEVEL}
            - LOG_PATH=${LOG_PATH}
        ports: 
            - 8090:8090
        networks: 
            webalytic_net:
                ipv4_address: 172.28.1.3

    hander:
        image: "handler"
        container_name: "webalytic_handler"
        restart: always
        volumes:
            - "/Users/tmorozov/Projects/data/webalytic:/mnt/log"
        environment: 
            - APP_NAME=handler
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_STREAM=${REDIS_STREAM}
            - REDIS_HANDLER=${REDIS_HANDLER}
            - REDIS_GROUP=${REDIS_GROUP}
            - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}
            - CLICKHOUSE_DBNAME=${CLICKHOUSE_DBNAME}
            - CLICKHOUSE_FLUSH_INTERVAL=${CLICKHOUSE_FLUSH_INTERVAL}
            - CLICKHOUSE_FLUSH_LIMIT=${CLICKHOUSE_FLUSH_LIMIT}
            - CLICKHOUSE_HTTP_PORT=${CLICKHOUSE_HTTP_PORT}
            - CLICKHOUSE_SERVICE_PORT=${CLICKHOUSE_SERVICE_PORT}
            - LOG_LEVEL=${LOG_LEVEL}
            - LOG_PATH=${LOG_PATH}
        ports: 
            - 8091:8091
        networks: 
            webalytic_net:
                ipv4_address: 172.28.1.4

    prometheus:
        image: "prom/prometheus:v2.30.0"
        volumes: 
            - "/Users/tmorozov/Projects/data/prometheus:/etc/prometheus"
            - prometheus_data:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/usr/share/prometheus/console_libraries'
            - '--web.console.templates=/usr/share/prometheus/consoles'
        ports:
            - 9090:9090
        links:
            - cadvisor:cadvisor
        depends_on:
            - cadvisor
        networks:
            - webalytic_net
        restart: always

    node-exporter:
        image: "prom/node-exporter"
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /../:/rootfs:ro
        command:
            - '--path.procfs=/host/proc'
            - '--path.sysfs=/host/sys'
            - --collector.filesystem.ignored-mount-points
            - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
        ports:
            - 9100:9100
        networks: 
            - webalytic_net
        restart: always
        deploy:
            mode: global

    cadvisor:
        image: "gcr.io/cadvisor/cadvisor"
        volumes:
            - /../:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
        ports:
            - 8080:8080
        restart: always
        networks:
            - webalytic_net
        deploy:
            mode: global

    grafana:
        image: grafana/grafana
        user: "472"
        depends_on:
            - prometheus
        ports:
            - 3000:3000
        volumes: 
            - grafana_data:/var/lib/grafana
            - "/Users/tmorozov/Projects/data/grafana/provisioning:/etc/grafana/provisioning"
        env_file:
            - /Users/tmorozov/Projects/data/grafana/config.monitoring
        networks:
            - webalytic_net
        restart: always
volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
    webalytic_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16