version: "3.9"

services:
    redis:
        image: "redis:6.2.3"
        container_name: "redis"
        restart: always
        ports: 
            - 6379:6379
        networks: 
            webalytic_net:
                ipv4_address: 172.28.1.2

    clickhouse:
        image: "yandex/clickhouse-server:21.6.4.26-alpine"
        container_name: "clickhouse"
        restart: always
        volumes:
            - "/Users/tmorozov/Projects/data/clickhouse:/var/lib/clickhouse"
        ports: 
            - 8123:8123
            - 9000:9000
        networks: 
            webalytic_net:
                ipv4_address: 172.28.1.5

    collector:
        image: "collector"
        container_name: "webalytic_collector"
        restart: always
        volumes:
            - "/Users/tmorozov/Projects/data/webalytic:/mnt/log"
        environment: 
            - APP_NAME=collector
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_STREAM=${REDIS_STREAM}
            - REDIS_HANDLER=${REDIS_HANDLER}
            - REDIS_GROUP=${REDIS_GROUP}
            - LOG_LEVEL=${LOG_LEVEL}
            - LOG_PATH=${LOG_PATH}
        ports: 
            - 8090:8090
        networks: 
            webalytic_net:
                ipv4_address: 172.28.1.3

    hander:
        image: "handler"
        container_name: "webalytic_handler"
        restart: always
        volumes:
            - "/Users/tmorozov/Projects/data/webalytic:/mnt/log"
        environment: 
            - APP_NAME=handler
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_STREAM=${REDIS_STREAM}
            - REDIS_HANDLER=${REDIS_HANDLER}
            - REDIS_GROUP=${REDIS_GROUP}
            - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}
            - CLICKHOUSE_DBNAME=${CLICKHOUSE_DBNAME}
            - CLICKHOUSE_FLUSH_INTERVAL=${CLICKHOUSE_FLUSH_INTERVAL}
            - CLICKHOUSE_FLUSH_LIMIT=${CLICKHOUSE_FLUSH_LIMIT}
            - CLICKHOUSE_HTTP_PORT=${CLICKHOUSE_HTTP_PORT}
            - CLICKHOUSE_SERVICE_PORT=${CLICKHOUSE_SERVICE_PORT}
            - LOG_LEVEL=${LOG_LEVEL}
            - LOG_PATH=${LOG_PATH}
        ports: 
            - 8091:8091
        networks: 
            webalytic_net:
                ipv4_address: 172.28.1.4

networks:
    webalytic_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16