apiVersion: v1
kind: Service
metadata:
  name: clickhouse-nodeport-service
spec:
  selector:
    app: clickhouse
  type: NodePort
  ports:
  - name: http-port
    port: 8123
    targetPort: 8123
    protocol: TCP
  - name: native-port
    port: 9000
    targetPort: 9000
    protocol: TCP
  - name: rep-port
    port: 9363
    targetPort: 9363
    protocol: TCP
