apiVersion: v1
kind: Service
metadata:
  name: consul-nodeport-service
spec:
  selector:
    app: consul
  type: NodePort
  ports:
  - name: http-api-port
    port: 8500
    targetPort: 8500
    protocol: TCP
  - name: wan-serf-port
    port: 8302
    targetPort: 8302
    protocol: TCP
  - name: lan-serf-port
    port: 8301
    targetPort: 8301
    protocol: TCP
  - name: dns-tcp-server-port
    port: 8600
    targetPort: 8600
    protocol: TCP
  - name: dns-udp-server-port
    port: 8600
    targetPort: 8600
    protocol: UDP
