apiVersion: v1
kind: Service
metadata:
  name: grafana-nodeport-service
spec:
  selector:
    app: grafana
  type: NodePort
  ports:
  - name: http-port
    port: 3000
    targetPort: 3000
    protocol: TCP

