apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport-service
spec:
  selector:
    app: prometheus
  type: NodePort
  ports:
  - name: http-port
    port: 9090
    targetPort: 9090
    protocol: TCP

